version: '3.8'

services:
  mongo:
    image: mongo:6.0.13
    container_name: chewata_app_db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: 
      context: ./backend        # points to the backend folder
      dockerfile: Dockerfile    # uses backend/Dockerfile
    container_name: chewata_app_backend
    ports:
      - "5000:5000"              # correct mapping: host:container
    env_file:
      - .env                     # make sure this file exists in root
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend        # assuming frontend/Dockerfile exists
    container_name: chewata_app_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo-data:
