#Deployment-Config
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chewata-frontend-deployment
  namespace: chewata-chat-app
  labels:
    app: chewata-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chewata-frontend
  template:
    metadata:
      labels:
        app: chewata-frontend
    spec:
      containers:
      - name: chewata-frontend
        image: emanuelafro/chewata_chat_app-frontend:1.0.1
        env: 
        - name: DANGEROUSLY_DISABLE_HOST_CHECK
          value: "true"
        ports:
          - containerPort: 3000
        resources:
          limits:
            cpu: "500m"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "1Gi"
        livenessProbe:    #Are you Alive?...Pod
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 60 # wait 10sec before first check
          periodSeconds: 60 # Every 30 seconds check
        readinessProbe: # Can you recive Traffic?...Application
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 60
#Ingress-Config          
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chewata-ingress
  namespace: chewata-chat-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: chewatachat.com
      http: 
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: chewata-frontend-service
              port:
                number: 80
#Service-Config
---
apiVersion: v1
kind: Service 
metadata:
  name: chewata-frontend-service
  namespace: chewata-chat-app
  labels:
    app: chewata-frontend
spec:
  type: ClusterIP
  selector:
    app: chewata-frontend 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
# Horizontal_Pod_Scaling
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: chewata-horizontal-pod-scaling
  namespace: chewata-chat-app
spec:
  scaleTargetRef: # Target to be scaled
    apiVersion: apps/v1
    kind: Deployment
    name: chewata-frontend-deployment
  minReplicas: 1
  maxReplicas: 5

  metrics:
    - type: Resource
      resource: 
        name: cpu
        target: 
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: 80       
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 15  # Scale-Down after 60 seconds
      policies: 
        - type: Percent
          value: 100   # maximum remove 50% of the  pods at a time
          periodSeconds: 30
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
