apiVersion: v1
kind: Service 
metadata:
  name: chewata-frontend-service
  namespace: default
  labels:
    app: chewata-frontend
spec:
  type: ClusterIP
  selector:
    app: chewata-frontend 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000