# -----------------------------
# 4️⃣ Prometheus ConfigMap
# -----------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: chewata-prometheus-config
  namespace: chewata-monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    rule_files:
      - /etc/prometheus/rules/chewata-rules.yml
    alerting:
      alertmanagers:
        - static_configs:
            - targets: ['chewata-alertmanager.chewata-monitoring.svc:9093']
    scrape_configs:
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace]
            action: keep
            regex: chewata-chat-app
    